### ISSUE TITLE
Warning in Pipeline

### ISSUE THREAD

**Issue by balazsorban44** [FabienLavocat/vsts-tasks#10]
Hi, awesome work, thanks!

I am getting the following warning in the console:

```
The names of some imported commands from the module 'AzureRM.Websites' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.
```
Is it a fixable issue, or can I just ignore it? It just shows this warning and I would like to silent it, if possible:
![https://i.imgur.com/LETx8Hn.png](https://i.imgur.com/LETx8Hn.png)

Is it maybe something on my side?

**Comment by FabienLavocat** [comment]
Thanks a lot for your feedback!
This is a warning from the Azure PowerShell cmdlets. It's simply an information. Nothing to worry about.
