### ISSUE TITLE
Purge reports a warning

### ISSUE THREAD

**Issue by Coreusa** [FabienLavocat/vsts-tasks#5]
Each time this module is run, it complains with a warning (albeit it succeeds). Here's an excerpt from the log:

```
##[command]Import-Module -Name C:\Program Files\WindowsPowerShell\Modules\AzureRM\2.1.0\AzureRM.psd1 -Global
##[warning]The names of some imported commands from the module 'AzureRM.Websites' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.
##[command]Import-Module -Name C:\Program Files\WindowsPowerShell\Modules\AzureRM.Profile\2.1.0\AzureRM.Profile.psm1 -Global
```

![bilde](https://user-images.githubusercontent.com/706874/56139969-3462c000-5f9a-11e9-9100-632a8327523b.png)

**Comment by FabienLavocat** [comment]
This warning comes from the Azure RM PowerShell module. I'll see if I can use a newer version.

**Comment by Coreusa** [comment]
![bilde](https://user-images.githubusercontent.com/706874/56804248-5cb5ae80-6825-11e9-8d1a-b641777baed7.png)

The module seems updated, and outputs **[debug]** info now.

**Comment by FabienLavocat** [comment]
But the warning is still here.

**Comment by dangrima90** [comment]
Hi @FabienLavocat I too am seeing this warning when the Purge CDN Task is run. The task is still being successful just curious to know if it's something I should worry about or not.

**Comment by FabienLavocat** [comment]
@dangrima90 nothing to worry about. It comes from the PowerShell module for Microsoft Azure that's installed on the DevOps Agent. They are using a verb that is not "approved" for a couple of CommandLets. (PowerShell doesn't like the name of the function) but it has 0 impact on the execution of the code.
