### ISSUE TITLE
Service connection on error

### ISSUE THREAD

**Issue by SimonChaveneau** [FabienLavocat/vsts-tasks#6]
Hi, 
I have the following error which wasn't here yesterday.
```csharp
Exception Message: The pipeline is not valid. Job Phase_1: Step PurgeAzureCDNEndpoint input ConnectedServiceName expects a service connection of type Azure but the provided service connection VSTS-Gyosa-DEV is of type azurerm. (type PipelineValidationException)
```

I updated from v1.* to v2.* but i get the same message. Idem after switching the Azure Connection Type.

Any idea why ?
Thanks

**Comment by SimonChaveneau** [comment]
Some feedback, looks like its due to an update on AzureDevOps side. 

https://developercommunity.visualstudio.com/content/problem/538728/release-failing-due-to-service-connection.html

**Comment by FabienLavocat** [comment]
Thanks for the link! I'll try to follow up on this issue.
Have you tried the different workaround provided?

**Comment by SimonChaveneau** [comment]
Yes, i removed your add-on and added a new Azure PowerShell script with the Unpublish-AzureRm.... which works right now.

**Comment by FabienLavocat** [comment]
Microsoft seems to have fixed the problem on their side. Thanks for reporting!
