### ISSUE TITLE
[error]Operation returned an invalid status code 'NotFound'

### ISSUE THREAD

**Issue by vohuythao** [FabienLavocat/vsts-tasks#7]
Hello, 

Thanks for your awesome plugin, but we currently got a trouble when use it in Azure Pipeline

2019-07-30T11:07:37.8116544Z ##[error]Operation returned an invalid status code 'NotFound'
2019-07-30T11:07:37.8437968Z ##[section]Finishing: Purge Azure CDN Endpoint

But the task in Azure Pipeline still return successful
I check in Azure Portal, the purge action is failed

Is there any guidance for us?
Thank you

**Comment by FabienLavocat** [comment]
Do you have logs in the Azure Portal that would give us some details on the reason for the failure?
Was it working before in the same pipeline?

**Comment by vohuythao** [comment]
Hello Fabien,

I saw in the JSON, it never got an Accept result

![image](https://user-images.githubusercontent.com/14121587/62634811-b4090600-b960-11e9-998a-87a594924afb.png)

Thank you

**Comment by FabienLavocat** [comment]
If you dive into the details of the Failed operation, do you get any message?

**Comment by vohuythao** [comment]
Yeah, thank you.
I think it is because my mistake when input the endpoint name.
It should NOT include the .azureedge.net

It is running well now
Thank you
